version: '3.2'
services:
  web:
    build: .
    container_name: "guestbookapp"
    ports:
      - "4000:4000"
    command: mix phx.server
    environment:
      - MIX_ENV=dev
      - PORT=4000
    volumes:
      - .:/app
  db:
    image: mysql:5.7.22
    ports:
      - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: passwd
        MYSQL_USER: guestbook
        MYSQL_PASSWORD: passwd
        MYSQL_DATABASE: guestbook
